name: Lint
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    # env:
    #   GITHUB_AUTH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
          registry-url: 'https://npm.pkg.github.com'

      - uses: pnpm/action-setup@v2.4.0
        with:
            version: 8.10.2

      # - name: Configure Phrase GitHub packages registry url & auth token
      #   run: |
      #     pnpm config set --global "npmScopes[phrase].npmRegistryServer" "https://npm.pkg.github.com"
      #     pnpm config set --global "npmScopes[phrase].npmAuthToken" "\${GITHUB_AUTH_TOKEN}"

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint
