name: NPM release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.2.2
      with:
          version: 7.5.0
    - name: Install dependencies
      run: pnpm install
    - name: Build package
      run: pnpm build
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@116647291d9b7bef1f5a4315deedd3f46ed4218b
      with:
        semantic_version: 17.0.7  # It is recommended to specify specifying version range
                                    # for semantic-release.
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
