name: Test coverage
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2

      - uses: pnpm/action-setup@v2.4.0
        with:
            version: 8.10.2

      - name: Install dependencies
        run: pnpm install

      - name: Run test coverage
        run: pnpm test.coverage
