name: Test coverage
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.5.0
          node-version: '16.x'
      - run: pnpm install
      - run: pnpm test.coverage
